{{- if .Values.istio.virtualservices.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "knative-helm-chart-example.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "knative-helm-chart-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  gateways:
  {{- range $key, $value := .Values.istio.virtualservices.gateways }}
  - {{ $value }}
  {{- end }}
  hosts:
  {{- range $key, $value := .Values.istio.virtualservices.hosts }}
  - {{ $value }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualservices.apiPath }}
    rewrite:
      authority: {{ template "knative-helm-chart-example.fullname" . }}.{{ .Release.Namespace }}.sajcloud.com.br
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100
{{- end }}          
